services:
  tickers-api:
    image: tickers-api:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
      - ASPNETCORE_HTTP_PORTS=5245
    ports:
      - "5245"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - C:\Dev2\shared:/home/app/shared